# Generated by Django 4.2.4 on 2023-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombreApellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
