# Generated by Django 4.2.4 on 2023-08-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('idEducacion', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('idExperiencia', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('posicion', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('idInvestigacion', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idProyecto', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
                ('descripcion', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('idSkill', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(max_length=1)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('porcentaje', models.IntegerField(max_length=100)),
            ],
        ),
    ]
