# Generated by Django 4.2.4 on 2023-08-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_skill_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='porcentaje',
            field=models.IntegerField(),
        ),
    ]
