# Generated by Django 4.2.5 on 2023-09-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_educacion_ideducacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='descripcion',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='titulo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
